version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: kivo-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    command: ['mongod', '--replSet', 'rs0', '--bind_ip_all']

volumes:
  mongo_data:
